### PR TITLE
Fix incorrect `ZipOpenFS.createReadStream().path`

### LINKED ISSUE #3094: [Bug?]: `fs.createReadStream(p).path` is not equals to `p`
### Self-service

- [x] I'd be willing to implement a fix

### Describe the bug

The `path` property of the `fs.ReadStream` object returned by calling `fs.createReadStream` is not equals to the `path` argument passed to `fs.createReadStream`.

### To reproduce

```js repro
await packageJsonAndInstall({
  dependencies: {
    'koa-static': '*',
  },
})

const requirePath = 'koa-static/package.json'
const resolvedPath = await node(`require.resolve(${JSON.stringify(requirePath)})`)
const streamPath = await node(`require('fs').createReadStream(${JSON.stringify(resolvedPath)}).path`)

expect(streamPath).toBe(resolvedPath)
```

### Environment

System:
  OS: Linux 5.10 Debian GNU/Linux 10 (buster) 10 (buster)
  CPU: (6) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
Binaries:
  Node: 16.3.0 - /tmp/xfs-5d57e4f5/node
  Yarn: 3.0.0-rc.6 - /tmp/xfs-5d57e4f5/yarn
  npm: 7.15.1 - /usr/local/bin/npm

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alvinleung1996**
**What's the problem this PR addresses?**

The `path` property of the stream object returned by `fs.createReadStream` incorrectly equals to the subpath of the file within the zip file.  This pull request fixes this issue by assigning the normalized full path (zip path + subpath) of the file to the `path` property of the stream object.

Fix #3094.

...

**How did you fix it?**

In `ZipOpenFS.createReadStream`, obtain the normalized full path by joining `archivePath` and `subpath` and patch the `path` property of the stream object returned by `ZipFS.createReadStream` with the full path.

...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

File: packages/yarnpkg-fslib/sources/ZipOpenFS.ts [hunk 1]
```diff
@@ -302,8 +302,10 @@ export class ZipOpenFS extends BasePortableFakeFS {
 
     return this.makeCallSync(p, () => {
       return this.baseFs.createReadStream(p, opts);
-    }, (zipFs, {subPath}) => {
-      return zipFs.createReadStream(subPath, opts);
+    }, (zipFs, {archivePath, subPath}) => {
+      const stream = zipFs.createReadStream(subPath, opts);
+      stream.path = this.pathUtils.join(archivePath, subPath);
```
Comment (paul-soporan) [inline packages/yarnpkg-fslib/sources/ZipOpenFS.ts:307]:
```suggestion
      // This is a very hacky workaround. `ZipOpenFS` shouldn't have to work with `NativePath`s.
      // Ref: https://github.com/yarnpkg/berry/pull/3774
      // TODO: think of a better solution
      stream.path = npath.fromPortablePath(this.pathUtils.join(archivePath, subPath));
```

File: .yarn/versions/a282bd58.yml [hunk 2]
```diff
@@ -0,0 +1,36 @@
+releases:
+  "@yarnpkg/fslib": patch
```
Comment (paul-soporan) [inline .yarn/versions/a282bd58.yml:2]: A few more packages need to be released:
- `@yarnpkg/pnp`, `@yarnpkg/plugin-pnp` for the PnP hook (and `yarn update:pnp:hook` needs to be run too)
- `vscode-zipfs` because it uses the `ZipOpenFS`
- `@yarnpkg/cli` because the hook changes affect the CLI
(I hope I didn't miss any)

**Review by paul-soporan — CHANGES_REQUESTED** [review]
This isn't fully correct since it will assign the `PortablePath` to the `ZipOpenFS` stream (which is correct), but the path won't be transformed into a `NativePath` by the `PosixFS` (which is a `ProxiedFS`).

Back when this issue was created I tried working on it but it's very tricky:
- We can either make FS instances assign the correct path type to the resulting stream, but to do this the `NodeFS` has to convert the path to a `PortablePath` which it can't do without using a `Proxy` because Node doesn't like us monkey-patching the `path` property (IIRC it uses it immediately after we monkey patch it and it fails). This is the only semantically correct solution but @arcanis doesn't want us to use proxies and I couldn't think of any other semantically correct solution so I left it unfinished.
- We can also always have the `path` always be a `NativePath`, but the case of a `ProxiedFS` wrapping a `NodeFS` would still be broken.

This PR is still better than the current situation where the path isn't correct (and somebody else can work later on the other parts), so the only change I'll request is converting the path to a `NativePath` so that the use case of patching `fs` works correctly.

File: .yarn/versions/a282bd58.yml (hunk 2 above)
Comment (alvinleung1996) [reply .yarn/versions/a282bd58.yml:2]: All the packages in `declined` depend on `@yarnpkg/fslib`, how can I decide which packages need to be released?

Comment (arcanis) [reply .yarn/versions/a282bd58.yml:2]: Since it's a patch you can leave them all as declined except the ones Paul mentioned (because those are bundling @yarnpkg/fslib, so they won't get the new version unless they are re-released).

**Comment by arcanis** [comment]
Thanks, @alvinleung1996!
