### PR TITLE
fix: make yarn up resolve latest for tag

### LINKED ISSUE #1419: [Bug] yarn up upgrade to latest tagged
- [ ] I'd be willing to implement a fix

**Describe the bug**

As already described in the issue #1414, `yarn up foo@canary` will not upgrade to the latest package tagged with the **canary** tag.

Like @arcanis mentioned:
> running `yarn up foo@canary` will literally set the range of your dependencies to canary. Since canary is already in the lockfile, it won't get re-locked. I think that should be considered as a bug 🤔

**To Reproduce**

```json
# package.json
{
  "dependencies": {
    "foo": "canary"
  }
}
````

```bash
yarn up foo@canary
```

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

`yarn up foo@tag` doesn't re-resolve `tag` if it's already part of the lockfile.

Fixes #1419.

**How did you fix it?**

- I added a new `project.forgetResolution` method - accepts both descriptors and locators as arguments.
- I made it so that `yarn up` calls this method if the current descriptor matches the updated descriptor. This "unlocks" the dependency, causing it to be resolved again to the latest satisfying version.

This means that now:
- `yarn up foo@canary` updates `foo` to the latest version resolved for the `canary` tag
- `yarn up foo@3.x` updates `foo` to the latest version resolved for the `3.x` range
- `yarn up foo@github-repo/foo` updates `foo` to the version resolved from the latest commit

Note: I removed the `hasChanged` part of `yarn up`, as we'd have to manually run `resolver.getCandidates` to see if the resolution changes, which would unnecessarily increase the execution time.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I have verified that all automated PR checks pass.

### CODE REVIEW

File: packages/yarnpkg-core/sources/Project.ts [hunk 1]
```diff
@@ -417,9 +417,25 @@ export class Project {
     }
   }
 
+  forgetResolution(descriptor: Descriptor): void
+  forgetResolution(locator: Locator): void
```
Comment (arcanis) [inline packages/yarnpkg-core/sources/Project.ts:421]:
```suggestion
  forgetResolution(descriptor: Descriptor): void;
  forgetResolution(locator: Locator): void;
```
