### PR TITLE
fix(doctor): fixes ArrayLiteralExpression error when running doctor with unmet peer dependency

### LINKED ISSUE #2752: [Bug] Yarn doctor 3.0.0-rc.2 crashes when there is a missing peer dependency
**Describe the bug**

So I think I found a bug with version `3.0.0-rc.2`, when there is a mising peer dependency, it no longer lists the missing peer dependency and instead crashes with an error message:

```
➤ YN0000: ┌ /Users/btea/git/repo/packages/access/package.json
➤ YN0001: │ Error: Invalid property type: ArrayLiteralExpression
    at buildJsonNode (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:167:19)
    at async checkForUnmetPeerDependency (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:187:26)
    at async processManifest (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:227:17)
    at async processWorkspace (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:244:5)
    at async /Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:311:29
    at async StreamReport.startTimerPromise (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/node_modules/@yarnpkg/core/lib/StreamReport.js:219:20)
    at async /Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:298:25
    at async Function.start (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/node_modules/@yarnpkg/core/lib/StreamReport.js:132:13)
    at async EntryCommand.execute (/Users/btea/.npm/_npx/8344/lib/node_modules/@yarnpkg/doctor/lib/cli.js:285:24)
```

**To Reproduce**

<details>
  <summary>Reproduction</summary>

  ```js repro
const { promises: fs } = require(`fs`);

await packageJsonAndInstall({
  dependencies: {
    [`react-dom`]: `^17.0.0`,
  },
});

await fs.writeFile(`index.js`, `import ReactDOM from 'react-dom'`);

await expect(yarn(`dlx`, `@yarnpkg/doctor`)).resolves.toMatch(
  "Unmet transitive peer dependency on react"
);
  ```
</details>

Also have a repo that minimally reproduces the problem: https://github.com/benatshippabo/yarn-doctor-bug

**Screenshots**

N/A

**Environment if relevant (please complete the following information):**

 - MacOS Big Sur
 - Node 12
 - Yarn version 3.0.0-rc.2

**Additional context**

_Originally posted by @benatshippabo in https://github.com/yarnpkg/berry/issues/2534#issuecomment-817996747_

### PR DESCRIPTION
**Pull request by benatshippabo**
**What's the problem this PR addresses?**

Fixes #2752 
...

**How did you fix it?**

Fixed a bad parameter when using `createSourceFile`
...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by arcanis** [comment]
It was intended, since `{"a": "b"}` is parsed differently in JS/TS than in JSON (a Block rather than an Expression).

**Comment by benatshippabo** [comment]
> It was intended, since `{"a": "b"}` is parsed differently in JS/TS than in JSON (a Block rather than an Expression).

Okay I changed the script target to`ts.ScriptTarget.JSON` which should parse the file properly according to the source code:
https://github.com/microsoft/TypeScript/blob/1294ee8c1f37c8bf214db67e180edb3220a52236/src/compiler/parser.ts#L631-L633. 

I'm wondering why it didn't crash when `buildJsonNode` was trying to parse the json file after I removed the parentheses now 🤔

File: packages/yarnpkg-doctor/sources/cli.ts [hunk 1]
```diff
@@ -192,8 +192,8 @@ async function buildJsonNode(p: PortablePath, accesses: Array<string>) {
 
   const sourceFile = await ts.createSourceFile(
     npath.fromPortablePath(p),
-    `(${content})`,
-    ts.ScriptTarget.ES2015,
+    content,
+    ts.ScriptTarget.JSON,
```
Comment (arcanis) [inline packages/yarnpkg-doctor/sources/cli.ts:196]: Completely missed this parse mode 😅
