### PR TITLE
Fix #5165 - missing executable perms when installing with pnpm linker

### LINKED ISSUE #5165: [Bug?]: Fail to install `turbo` when using `nodeLinker: pnpm` with v4
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

After upgrading to yarn v4 (canary), when run `yarn install` will lead to the following error on `turbo`.

```
# This file contains the result of Yarn building a package (turbo@npm:1.5.5)
# Script name: postinstall

node:internal/errors:863
  const err = new Error(message);
              ^

Error: Command failed: node /node_modules/.store/turbo-npm-1.5.5-30714db15d/package/bin/turbo --version
/node_modules/.store/turbo-npm-1.5.5-30714db15d/package/bin/turbo:13
    throw e;
    ^

<ref *1> Error: spawnSync /node_modules/.store/turbo-darwin-arm64-npm-1.5.5-80deeb5941/package/bin/turbo EACCES
    at Object.spawnSync (node:internal/child_process:1110:20)
    at spawnSync (node:child_process:857:24)
    at Object.execFileSync (node:child_process:900:15)
    at Object.<anonymous> (/node_modules/.store/turbo-npm-1.5.5-30714db15d/package/bin/turbo:6:28)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawnSync /node_modules/.store/turbo-darwin-arm64-npm-1.5.5-80deeb5941/package/bin/turbo',
  path: '/node_modules/.store/turbo-darwin-arm64-npm-1.5.5-80deeb5941/package/bin/turbo',
  spawnargs: [ '--version' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 26749,
  stdout: null,
  stderr: null
}
```

When using yarn v3, can be install successfully.

### To reproduce

```js repro
const {promises: {writeFile}} = require(`fs`);

// Enable `pnpm` nodeLinker
await writeFile('.yarnrc.yml', 'nodeLinker: pnpm');

await packageJson({
  devDependencies: {
    [`turbo`]: `^1.5.5`,
  }
});

await expect(yarn(`install`)).rejects.not.toThrow(`Command failed`);;

```

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.12.1 - /private/var/folders/bl/b4w8tgms0qdf3g_dp8_8nspr0000gn/T/xfs-cb43a611/node
    Yarn: 4.0.0-rc.34 - /private/var/folders/bl/b4w8tgms0qdf3g_dp8_8nspr0000gn/T/xfs-cb43a611/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fancyfractal**
**What's the problem this PR addresses?**

This is the fix for missing executable perms when installing dependencies like turbo and esbuild with pnpm linker (https://github.com/yarnpkg/berry/issues/5165, https://github.com/yarnpkg/berry/issues/5991)

Resolves #5165

**How did you fix it?**

Looks like the code was missing for setting permissions for the file copied by pnpm linker into content-addressable store 

I added `destinationFs.chmodPromise` to `copyFileViaIndex` in `fslib` if the file is not in store (`if (!indexStat)` branch)

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

File: packages/yarnpkg-fslib/sources/algorithms/copyPromise.ts [hunk 1]
```diff
@@ -263,8 +263,13 @@ async function copyFileViaIndex<P1 extends Path, P2 extends Path>(prelayout: Ope
   });
 
   postlayout.push(async () => {
-    if (!indexStat)
+    if (!indexStat) {
       await destinationFs.lutimesPromise(indexPath, defaultTime, defaultTime);
+      const mode = sourceStat.mode & 0o777;
+      if (mode !== 0o644) {
+        await destinationFs.chmodPromise(indexPath, sourceStat.mode);
+      }
```
Comment (arcanis) [inline packages/yarnpkg-fslib/sources/algorithms/copyPromise.ts:271]: Doesn't that have a risk to corrupt the index if two packages have the same file with different chmod? I think we need to add the chmod to the index file name if it's not 644 to prevent this ([here](https://github.com/yarnpkg/berry/blob/ceed12d9b7e75102fb5884641dbaa055ccc6c064/packages/yarnpkg-fslib/sources/algorithms/copyPromise.ts#L176)).

Comment (fancyfractal) [reply packages/yarnpkg-fslib/sources/algorithms/copyPromise.ts:271]: Yes I did not think about that - added one more commit
