### PR TITLE
Switch to typescript for compilation to generate .d.ts files

### LINKED ISSUE #707: [Bug] @yarnpkg packages don't contain type definitions
- [ ] I'd be willing to implement a fix

**Describe the bug**

Installing `@yarnpkg/core`, `@yarnpkg/pnpify` etc. only installs javascript files. There are no typescript definitions in the published packages.

**To Reproduce**

```js repro
const {promises: {writeFile}} = require(`fs`);

await packageJsonAndInstall({
  devDependencies: {
    [`@yarnpkg/core`]: `^2.0.0-rc.19`,
    [`typescript`]: `^3.6.3`
  }
});

await writeFile(`index.ts`, `
import {Plugin} from '@yarnpkg/core';

// note: wrong code on purpose, because we expect a compilation failure below
const foo: Plugin = 'not a plugin';
`);

await expect(yarn(`tsc`, `--noImplicitAny`, `index.ts`)).rejects.not.toThrow(
  /Could not find a declaration file for module '@yarnpkg\/core'/
);
```

**Screenshots**

image

### PR DESCRIPTION
**Pull request by bgotink**
Switch to the typescript compiler instead of babel to output `.d.ts` files next to the `.js` files.
Use a custom compile script instead of `tsc` to allow for a single `tsconfig.json` file for the entire berry project.

Fixes #707 

I still need to make some changes to the commands, because typescript is now complaining about the `usage` properties, but I wanted feedback on the setup before starting on that.

```
$ yarn packages/plugin-essentials prepack
sources/commands/add.ts(44,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/bin.ts(14,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/cache/clean.ts(14,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/config.ts(18,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/config/get.ts(10,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/config/set.ts(13,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/install.ts(42,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/link.ts(20,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/node.ts(11,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/plugin/import.ts(15,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/plugin/list.ts(17,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/plugin/runtime.ts(7,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/rebuild.ts(12,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/remove.ts(18,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/run.ts(34,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/set/resolution.ts(17,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/set/version.ts(22,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/set/version/sources.ts(57,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/up.ts(31,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/why.ts(22,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.

sources/commands/workspaces/list.ts(15,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.```

### CODE REVIEW

File: scripts/compile.js [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+  return 1;
+}
+
+/**
+ * @param {string} folder
+ * @returns {import('typescript').FormatDiagnosticsHost}
+ */
+function getFormatDiagnosticsHost(folder) {
+  return {
+    getCurrentDirectory: () => folder,
```
Comment (bgotink) [inline scripts/compile.js]: Passing the folder being built leads to errors that are logged relative to the package folder, like in the OP

```
sources/commands/workspaces/list.ts(15,10): error TS2742: ...
```

An alternative would be to use the repository root, to log the path of the file in the repo instead:

```
packages/plugin-essentials/sources/commands/workspaces/list.ts(15,10): error TS2742: ...
```

Any opinions?

**Comment by eps1lon** [comment]
We could've kept the old babel transpilation infra an use `tsc --emitDeclarationOnly` if missing types were the only issue.

I feel like the actual issue is that we need a custom script to use a single tsconfig. We should set up the project properly to recognize all packages. Might need more `tsconfig.json` but these should only contain a single `extends` entry.

**Comment by bgotink** [comment]
> We could've kept the old babel transpilation infra an use tsc --emitDeclarationOnly if missing types were the only issue.

Is there a benefit to using babel + tsc instead of only tsc?

> I feel like the actual issue is that we need a custom script to use a single tsconfig. We should set up the project properly to recognize all packages. Might need more tsconfig.json but these should only contain a single extends entry.

It's a tradeoff between standard tsc binary + more configuration versus non-standard typescript compilation via their API.

I went ahead and tried it out with multiple tscfongis. It's a bit more work than just adding a `tsconfig.json` per package with `{"extends": "../../tsconfig"}`.

Typescript needs more properties, because some paths are relative to the tsconfig file, not the project:

```jsonc
// packages/*/tsconfig.json
{
  "extends": "../../tsconfig",
  "compilerOptions": {
    "rootDir": "sources",
    "outDir": "lib"
  },
  "include": ["sources/**/*"]
}
```

We also need to add `@types/node` to just about every package's dependencies/devDependencies and `@types/emscriptem` to the dependencies/devDependencies of the libzip package.

I'm in favour of keeping the amount of boilerplate low, but that's my personal opinion.

File: scripts/compile.js (hunk 1 above)
Comment (arcanis) [reply scripts/compile.js]: Slight preference on the second one to avoid ambiguities with `index.ts` etc

**Comment by arcanis** [comment]
We used to have the `tsconfig` in each directory, but it was fairly verbose and could get out of sync. Maybe on the long term using constraints would be an acceptable solution too (`gen_enforced_file`, or something similar?).

For now we need *something* though, so I'm ok if we use a script as long as it's not as big as `Project.ts` 😝

**Comment by arcanis** [comment]
I merged too quickly, there's still the `usage` thing. @bgotink do you have an idea what might cause thing?
