### PR TITLE
Fixes bugs in yarn npm audit

### LINKED ISSUE #5824: [Bug?]: excluding specific deprecated package doesn't work for npm audit
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I want to ignore a specific deprecated package.

I run :
```
yarn npm audit --recursive --all --severity info --environment production --exclude sourcemap-codec
```

Expected output:
```
➤ YN0001: No audit suggestions
```

Actual output:
```
└─ sourcemap-codec
   ├─ ID: sourcemap-codec (deprecation)
   ├─ Issue: Please use @jridgewell/sourcemap-codec instead
   ├─ Severity: moderate
   ├─ Vulnerable Versions: 1.4.8
   │ (\n)?
   │ (\n)?
   ├─ Tree Versions
   │  └─ 1.4.8
   └─ Dependents
      └─ magic-string@npm:0.25.1
```

### To reproduce

Install sourcemap-codec directly or as peer-dependency (for example with magic-string@npm:0.25.1).

Run:
```
yarn npm audit --recursive --all --severity info --environment production --exclude sourcemap-codec
```

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
  Binaries:
    Node: 18.18.1 - C:\Users\BASNIJ~1\AppData\Local\Temp\xfs-8011ae2b\node.CMD
    Yarn: 4.0.0 - C:\Users\BASNIJ~1\AppData\Local\Temp\xfs-8011ae2b\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

_No response_

### LINKED ISSUE #5830: [Bug?]: npm audit --json output vulnerabilities that are in --ignore
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When using both --json and --ignore, the json output include the vulnerabilities that are in the ignore list

### To reproduce

```json
{
  "packageManager": "yarn@4.0.0",
  "dependencies": {
    "nth-check": "1.0.2"
  }
}
```
`yarn npm audit --ignore 1093882 --json`
output
```json
{"nth-check":[{"id":1093882,"url":"https://github.com/advisories/GHSA-rp65-9cf3-cjxr","title":"Inefficient Regular Expression Complexity in nth-check","severity":"high","vulnerable_versions":"<2.0.1","cwe":["CWE-1333"],"cvss":{"score":7.5,"vectorString":"CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"}}]}
```

while
```yarn npm audit --ignore 1093882```
output
`➤ YN0001: No audit suggestions`

NB: in both case (with or without --json) the command exit code takes correcly into account the --ignore parameters

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
  Binaries:
    Node: 20.8.1 - C:\Users\xxxxx\AppData\Local\Temp\xfs-2cd2ed2f\node.CMD
    Yarn: 4.0.0 - C:\Users\xxxxx\AppData\Local\Temp\xfs-2cd2ed2f\yarn.CMD
    npm: 10.1.0 - D:\scoop\apps\nodejs\current\npm.CMD
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by arcanis**
**What's the problem this PR addresses?**

The rewrite of `yarn npm audit` broke a couple of things in the advisory reporting.

Fixes #5824 - The `--exclude` filter wasn't applied to deprecations
Fixes #5830 - The `--json` output was printing the raw registry output, not the filtered tree

**How did you fix it?**

Fixed the deprecation iterations (we were iterating the unfiltered data).

Fixed the json reporting to instead print the same tree as the one we would have displayed outside of `--json`. It's _technically_ a breaking change, but it was supposed to be like that so it's probably fine to treat it as a 7.0.1 bugfix.

Added tests to prevent regressions.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

File: packages/plugin-npm-cli/sources/commands/npm/audit.ts [hunk 1]
```diff
@@ -131,12 +131,12 @@ export default class NpmAuditCommand extends BaseCommand {
         registry,
       }) as unknown as Promise<npmAuditTypes.AuditResponse>;
 
-      const deprecations = await Promise.all(this.noDeprecations ? [] : Array.from(packages, async ([packageName, versions]) => {
+      const deprecations = await Promise.all(this.noDeprecations ? [] : Array.from(Object.entries(payload), async ([packageName, versions]) => {
```
Comment (wojtekmaj) [inline packages/plugin-npm-cli/sources/commands/npm/audit.ts:134]: While at it, why not lift `this.noDeprecations` check and avoid Promise.all call?
 
```suggestion
      const deprecations = this.noDeprecations ? [] : await Promise.all(Array.from(Object.entries(payload), async ([packageName, versions]) => {
```
