### PR TITLE
Handle propogating SIGTERM to spawned child processes

### LINKED ISSUE #1741: [Bug] Unable to catch signals using Docker
- [ ] I'd be willing to implement a fix

**Describe the bug**

To perform a graceful shutdown of containers we need a way to catch the signals (SIGTERM/SIGINT) that Docker sends when shutting down a container.  In yarn v1 the workaround was to use `node <script>` directly instead of `yarn run`. However I can't seem to get this to work using `yarn node <script>` or `yarn run` in v2 with PnP enabled.

**To Reproduce**

Use a minimal Dockerfile:

```Dockerfile
FROM node:12.18.3

WORKDIR /opt/app

COPY . /opt/app

RUN yarn install

CMD ["yarn", "node", "./src"]
```

Inside src/index.js, listen for signals
```js
const signals = [SIGHUP, SIGINT, SIGTERM]
for (const signal of signals) {
   process.on(signal, () => {
      console.log(`process received a ${signal} signal`)
   })
}
```

Then when the container kill it using:
```sh
docker kill -s SIGTERM <container name>
```

**Environment if relevant (please complete the following information):**

 - OS: Docker
 - Node version 12.18.3
 - Yarn version 2.1.1

**Additional context**

I also tried using `docker-init/tini` to play around the PID 1 restriction after reading https://github.com/yarnpkg/berry/issues/991 but that doesn't seem to work either. It would be nice if there is some way to forward signals to the child processes so that yarn v2 works nicely with Docker.

### PR DESCRIPTION
**Pull request by ganemone**
**What's the problem this PR addresses?**

Fixes #1741
See https://github.com/albertywu/yarn2-termination-bug#repro for more context
...

**How did you fix it?**

Add SIGTERM listener to the yarn process and send signal to spawned child process if still running. The current approach will add a new SIGTERM listener to the yarn process for each child process spawned, removing the listener when the child process closes. If this is a concern, we could go with an alternative approach that keeps track of the child process refs in a Set and use a single listener to close all child processes running when the yarn process receives SIGTERM.

NOTE: The current PR only addresses this in the `pipevp` function in `execUtils`, not the `execvp` function. Its unclear to me if the same problem can present itself in usage of the `execvp` function, but we can easily add the same functionality there.
...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by andreialecu** [comment]
I looked over the repro you linked and it doesn't seem that your changes fix it.

I experimented a bit and moving your changes around here: https://github.com/yarnpkg/berry/blob/63a77b5a8628172b0f96a037b7259051c59f7a95/packages/yarnpkg-shell/sources/pipe.ts#L50-L54 do help

However, the yarn v1 wrapper seems to have the same bug. `SIGTERM` on yarn v1 will not kill yarn v2.

Made a small screen recording of the behavior [here](https://www.icloud.com/iclouddrive/02wHDbfwJ1ME3SABLtzrI9e9A#Screen_Recording_2021-01-08_at_13.51) (you can use "Download a Copy")

[Some more context from Discord](https://discord.com/channels/226791405589233664/226793713722982400/797052226904391691)

**Comment by andreialecu** [comment]
I sent a PR to fix the issue in yarn v1 here: https://github.com/yarnpkg/yarn/pull/8543

**Comment by andreialecu** [comment]
```
➜ ./repro.sh                     
2.4.0-git.20210107.hash-f13c07ba
killing yarn process: 66664
got sigterm
[PASS] done sleeping
```

With above v1 PR and with the below fix at: https://github.com/yarnpkg/berry/blob/63a77b5a8628172b0f96a037b7259051c59f7a95/packages/yarnpkg-shell/sources/pipe.ts#L54-L56
```ts
    const sigtermHandler = () => {
      child.kill(`SIGTERM`);
    }
    process.on(`SIGTERM`, sigtermHandler);
```

**Comment by ganemone** [comment]
@andreialecu I'm focused right now on solving the issue for yarn2 not using the yarn1 wrapper. We can follow up with a fix for yarn1 if necessary. I did double check and my changes do fix the issue when running `yarn node <script>`.

**Comment by andreialecu** [comment]
Here's a diff with tests:

```diff
diff --git a/packages/acceptance-tests/pkg-tests-specs/sources/commands/exec.test.js b/packages/acceptance-tests/pkg-tests-specs/sources/commands/exec.test.js
index 94ba01f5..80f9cad2 100644
--- a/packages/acceptance-tests/pkg-tests-specs/sources/commands/exec.test.js
+++ b/packages/acceptance-tests/pkg-tests-specs/sources/commands/exec.test.js
@@ -26,5 +26,29 @@ describe(`Commands`, () => {
         });
       })
     );
+
+    test(
+      `it should end child process on SIGTERM`,
+      makeTemporaryEnv({}, async ({ path, run, source }) => {
+        await xfs.writeFilePromise(`${path}/test.sh`, ([
+          `yarn node -e "console.log('Testing exec SIGTERM'); setTimeout(() => {}, 10000)" &`,
+          `sleep 1`,
+          `ps | grep -v "grep" | grep -q "Testing exec SIGTERM" || exit 1`, // check if it was started properly
+          `kill $!`,
+          `sleep 1`,
+          `if ps | grep -v "grep" | grep -q "Testing exec SIGTERM"`,
+          `then`,
+          `  echo "[FAIL] still running"; exit 1`,
+          `else`,
+          `  echo "[PASS] ok"; exit 0`,
+          `fi`
+        ]).join('\n'));
+
+        await expect(run(`exec`, `bash`, `test.sh`)).resolves.toMatchObject({
+          code: 0,
+          stdout: expect.stringContaining(`PASS`),
+        });
+      })
+    );
   });
 });
diff --git a/packages/acceptance-tests/pkg-tests-specs/sources/commands/run.test.js b/packages/acceptance-tests/pkg-tests-specs/sources/commands/run.test.js
index 4b031094..389ab8fd 100644
--- a/packages/acceptance-tests/pkg-tests-specs/sources/commands/run.test.js
+++ b/packages/acceptance-tests/pkg-tests-specs/sources/commands/run.test.js
@@ -1,3 +1,5 @@
+const {xfs} = require(`@yarnpkg/fslib`);
+
 describe(`Commands`, () => {
   for (const [description, args] of [[`with prefix`, [`run`]], [`without prefix`, []]]) {
     describe(`run ${description}`, () => {
@@ -123,6 +125,7 @@ describe(`Commands`, () => {
         },
       ),
     );
+
     test(`it should print the list of available scripts if no parameters passed to command`,
       makeTemporaryEnv(
         {
@@ -137,5 +140,35 @@ describe(`Commands`, () => {
         }
       )
     );
+
+    test(
+      `it should end child script on SIGTERM`,
+      makeTemporaryEnv({
+        scripts: {
+          sleep: `node -e "console.log('Testing script SIGTERM'); setTimeout(() => {}, 10000)"`
+        }
+      }, async ({ path, run, source }) => {
+        await run(`install`);
+        
+        await xfs.writeFilePromise(`${path}/test.sh`, ([
+          `yarn sleep &`,
+          `sleep 1`,
+          `ps | grep -v "grep" | grep -q "Testing script SIGTERM" || exit 1`, // check if it was started properly
+          `kill $!`,
+          `sleep 1`,
+          `if ps | grep -v "grep" | grep -q "Testing script SIGTERM"`,
+          `then`,
+          `  echo "[FAIL] still running"; exit 1`,
+          `else`,
+          `  echo "[PASS] ok"; exit 0`,
+          `fi`
+        ]).join('\n'));
+
+        await expect(run(`exec`, `bash`, `test.sh`)).resolves.toMatchObject({
+          code: 0,
+          stdout: expect.stringContaining(`PASS`),
+        });
+      })
+    );
   });
 });
```

**Comment by arcanis** [comment]
Nice, thank you both! @ganemone can you add the tests from @andreialecu to your PR? Perhaps we can even make a dedicated file in `features/signal.test.ts`, we start to have various signal behaviours to check 🤔

File: packages/yarnpkg-shell/sources/pipe.ts [hunk 1]
```diff
@@ -53,6 +53,9 @@ export function makeProcess(name: string, args: Array<string>, opts: ShellOption
       stderr,
     ]});
 
+    const sigtermHandler = () => child.kill(`SIGTERM`);
+    process.on(`SIGTERM`, sigtermHandler);
```
Comment (merceyz) [inline packages/yarnpkg-shell/sources/pipe.ts:57]: Isn't adding all these SIGTERM handlers goign to make node complain?

Comment (arcanis) [reply packages/yarnpkg-shell/sources/pipe.ts:57]: It might with `yarn workspaces foreach`, yep. @ganemone can you use a similar refcount to register a single callback, and keep track of the children manually in a set?

Comment (ganemone) [reply packages/yarnpkg-shell/sources/pipe.ts:57]: it is possible if you are spawning many concurrent things, but we do remove the handler when the child process closes. We could alternatively keep track of active children in a Set in parent scope and use a single global listener.

Comment (merceyz) [reply packages/yarnpkg-shell/sources/pipe.ts:57]: Do we need to explicitly forward the SIGINT as well? :thinking:

Comment (arcanis) [reply packages/yarnpkg-shell/sources/pipe.ts:57]: No, iirc SIGINT is purposefully ignored because the shell already sends it to the whole process tree, so we exit once the children have caught it and exited cleanly. I think there are discussions about that (perhaps on Discord).

Comment (andreialecu) [reply packages/yarnpkg-shell/sources/pipe.ts:57]: FWIW if you try to run `kill -s SIGINT <yarn_pid>` nothing happens. Should it not be forwarded to the child process?

Comment (andreialecu) [reply packages/yarnpkg-shell/sources/pipe.ts:57]: I'm not sure under which circumstances yarn itself might receive a SIGINT though. I can't think of any, but I'm not sure why forwarding it should be prevented.

Babel for example forwards it to itself: https://github.com/babel/babel/blob/master/packages/babel-node/src/babel-node.js#L99

Comment (arcanis) [reply packages/yarnpkg-shell/sources/pipe.ts]: The *shell* sends it to the whole process tree. Using `kill` doesn't. More details [here](https://github.com/yarnpkg/berry/issues/991#issuecomment-627947599).

In any case, this is intentional, SIGINT is working as expected. Babel doesn't have to work with many types of binaries, some of them behaving weirdly if they receive the same signal multiple times 🙂

**Comment by ganemone** [comment]
@arcanis finding a way to test this reliably is pretty difficult. I'm removing the tests for now

File: packages/yarnpkg-core/sources/execUtils.ts [hunk 2]
```diff
@@ -33,6 +34,15 @@ function sigintHandler() {
...
 let sigintRefCount = 0;
 
+const activeChildren = new Set<ChildProcess>();
+function sigtermHandler() {
+  for (const child of activeChildren) {
+    child.kill();
+  }
+}
+
+process.on(`SIGTERM`, sigtermHandler);
```
Comment (merceyz) [inline packages/yarnpkg-core/sources/execUtils.ts:44]: Needs to follow the same refcount logic as the `SIGINT` event

File: packages/yarnpkg-core/sources/execUtils.ts [hunk 3]
```diff
@@ -33,6 +34,15 @@ function sigintHandler() {
 // longer needed.
 let sigintRefCount = 0;
 
+const activeChildren = new Set<ChildProcess>();
+function sigtermHandler() {
+  for (const child of activeChildren) {
+    child.kill();
+  }
```
Comment (merceyz) [inline packages/yarnpkg-core/sources/execUtils.ts:41]: Need to clear the set after sending the kill signals

**Review by merceyz — CHANGES_REQUESTED** [review]

File: packages/yarnpkg-core/sources/execUtils.ts (hunk 3 above)
Comment (arcanis) [reply packages/yarnpkg-core/sources/execUtils.ts:41]: I think that's fine, since the processes may decide to ignore the signal until a later time.

Comment (ganemone) [reply packages/yarnpkg-core/sources/execUtils.ts:41]: I don't think it matters since our process is exiting after this handler completes

**Comment by arcanis** [comment]
I've made a few fixes to unify the SIGINT / SIGTERM handling, and removed the `execvp` part since it's not clear whether it useful, and in this sort of case I prefer to err on the side of the status quo (at least until we find a practical case where it matters). If the tests pass I think it's good to ship.

File: packages/yarnpkg-core/sources/execUtils.ts (hunk 3 above)
Comment (merceyz) [reply packages/yarnpkg-core/sources/execUtils.ts:37]: @ganemone No, we still wait for all children to terminate

**Comment by bervol** [comment]
Is there a planned release date for this bugfix?
As long as SIGTERM signals to a Docker container aren't propagated to Yarn 2 child processes, shipping Yarn 2 Docker containers is pretty cumbersome.

**Comment by arcanis** [comment]
It'll be part of the next major. If you want to use it now, you can run `yarn set version from sources` (plugins will need to be updated too using `yarn plugin import from sources`).

**Comment by merceyz** [comment]
> shipping Yarn 2 Docker containers is pretty cumbersome.

Assuming you meant Yarn PnP then you can run it without using the CLI - https://yarnpkg.com/features/pnp#initializing-pnp

**Comment by andreialecu** [comment]
@bervol as a workaround: you can bypass `yarn` by running your scripts via `node` directly:

If you use pnp you need to load the pnp hook:

```
node -r ./.pnp.js server.js
```

If you use yarn 1 to spawn yarn 2, note that bumping just v2 to sources isn't enough, because v1 has the same problem:

https://github.com/yarnpkg/yarn/pull/8543

**Comment by WesCossick** [comment]
Passing `SIGTERM` seems to have been released with Yarn 3.0.0. We're using Yarn 3.0.2 inside Docker, and are still noticing `SIGTERM` signals aren't propagated to the child process.

In our Dockerfile, we've got:

```Dockerfile
ENTRYPOINT yarn workspace example-workspace run start
```

And then in that workspace's `package.json` file we've got:

```json
"scripts": {
    "start": "node --unhandled-rejections=strict ./entry.js"
}
```

Should we expect `SIGTERM` signals to be propagated in this configuration?

**Comment by WesCossick** [comment]
@merceyz I did see that comment, yes. In many of our company's Docker images we manually install the latest version of Yarn (1.22.15 right now), but in the Docker image I was using for testing, it turns out it was just using the version of Yarn bundled with the `node` Docker image, which happens to be pretty outdated (1.22.5). I didn't catch that and assumed it was using the latest version like our other images.

Upgrading Yarn v1 from 1.22.5 to 1.22.15 fixed the issue.

There's been some recent discussions and steps taken to upgrade the version of Yarn bundled with Node.js's official Docker images: https://github.com/nodejs/docker-node/issues/1542. Seems like they should be updated in the near future.

In the meantime, for others who find this, you can add the following instruction to update Yarn:

```Dockerfile
RUN npm install -g yarn@1.22.15 --force
```
