### PR TITLE
fix(core): fix project.forgetResolution

### LINKED ISSUE #1507: [Bug] Canary builds including commit hash are not resolved correctly
- [ ] I'd be willing to implement a fix

**Describe the bug**

When releasing canary builds with lerna - the convention is relasing it with `x.y.z-canary.n+commit_hash`, which is semver compatible and will always result as `x.y.z-canary.n` on the registry.
When using `yarn up foo@canary` it throws following Error: `Error: foo@npm:^0.5.1-canary.155+2c22234: Expected the resolution to have been successful - package not found`.

**To Reproduce**

The yarn.lock describing the problem:

```
"my-package@workspace:packages/my-package":
  version: 0.0.0-use.local
  resolution: "my-package@workspace:packages/my-package"
  dependencies:
    "bar": canary
    "foo": canary
  languageName: unknown
  linkType: soft

"foo@npm:^0.5.1-canary.155+2c22234, foo@npm:canary":
  version: 0.5.1-canary.155
  resolution: "foo@npm:0.5.1-canary.155"
  checksum: 074ee04c95baf2ba6444f3d29ce085ebc47bab855d9d371db90de5dd17b88f5bcbf3592c25545008697f168f4e17bd20b47353c4c71da05465308ce1c45dba87
  languageName: node
  linkType: hard

"bar@npm:canary":
  version: 2.2.7-canary.117
  resolution: "bar@npm:2.2.7-canary.117"
  dependencies:
    "foo": ^0.5.1-canary.155+2c22234
  checksum: 0c8b6460848001803bd80d8bf02255bb7019404f1329f466b6fa4e59722ac0b0af8994b76f3e62805864f63ec52ecb9b771d3b07fd960219f2a8860903601910
  languageName: node
  linkType: hard
```

<details>
  <summary>Reproduction</summary>

  ```js repro
  const installPromise = packageJsonAndInstall({
  dependencies: {
  [`@polka/url`]: `next`,
  [`polka`]: `next`,
  },
  });

  await expect(installPromise)
  .resolves.toBeTruthy();

  const updatePromise = yarn(`up`, `@polka/*@next`);

  await expect(updatePromise)
  .resolves.toBeTruthy();
  ```

---
</details>

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

Calling `project.forgetResolution` with a `Descriptor` also deletes the resolved `Locator`, which can be part of multiple resolutions.

Fixes #1507.

**How did you fix it?**

I split the logic inside `project.forgetResolution` between Descriptors and Locators, and I've also added some extra deletions for Locators.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I have verified that all automated PR checks pass.

### CODE REVIEW

File: packages/yarnpkg-core/sources/Project.ts [hunk 1]
```diff
@@ -425,16 +425,30 @@ export class Project {
...
-      if (doDescriptorHashesMatch || doLocatorHashesMatch) {
-        this.storedDescriptors.delete(descriptorHash);
-        this.storedResolutions.delete(descriptorHash);
-        this.originalPackages.delete(locatorHash);
+    // Forgetting a descriptor requires:
+    // - deleting the resolution of the descriptor
+    // - deleting the descriptor
+    if (`descriptorHash` in dataStructure) {
+      this.storedResolutions.delete(dataStructure.descriptorHash);
+      this.storedDescriptors.delete(dataStructure.descriptorHash);
```
Comment (arcanis) [inline packages/yarnpkg-core/sources/Project.ts:433]: Shouldn't we still delete the locator if there's no other reference to it? That might be very expensive though, unless we build a reference map beforehand 🤔 

Basically, I'm worried that the remaining `originalPackage` will prevent the package metadata from being updated when calling `yarn up` (since the old ones would linger).

Comment (arcanis) [reply packages/yarnpkg-core/sources/Project.ts:433]: Actually the perf is moot - `forgetResolution` is only called with a descriptor inside `yarn up`, outside of a critical loop. So it won't be a problem even if we iterate to find all the usage.

Comment (paul-soporan) [reply packages/yarnpkg-core/sources/Project.ts]: Done. 👍
