### PR TITLE
 fix(plugin-github): parse new style github urls 

### LINKED ISSUE #1317: [Bug] CLI rc.33 breaks github protocol dependencies
- [ ] I'd be willing to implement a fix

**Describe the bug**

Something changed with how yarn resolves github URLs recently, and now `github:` dependencies fail with a 404 error.

**To Reproduce**

In a yarn 2 project with `2.0.0-rc.33` installed:

```console
$ yarn add left-pad@github:left-pad/left-pad
➤ YN0000: ┌ Resolution step
➤ YN0013: │ left-pad@https://github.com/left-pad/left-pad.git#commit=2fca6157fcca165438e0f9495cf0e5a4e6f71349 can't be found in the cache and will be fetched from GitHub
j [HTTPError]: Response code 404 (Not Found)
    at i.<anonymous> (/home/kherock/test/.yarn/releases/yarn-2.0.0-rc.33.js:10:403654)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: undefined
}
➤ YN0013: │ left-pad@github:left-pad/left-pad#commit=2fca6157fcca165438e0f9495cf0e5a4e6f71349 can't be found in the cache and will be fetched from the remote repository
➤ YN0000: └ Completed in 1.32s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ left-pad@https://github.com/left-pad/left-pad.git#commit=2fca6157fcca165438e0f9495cf0e5a4e6f71349 can't be found in the cache and will be fetched from GitHub
➤ YN0000: ⠙ ========================================----------------------------------------
j [HTTPError]: Response code 404 (Not Found)
    at i.<anonymous> (/home/kherock/test/.yarn/releases/yarn-2.0.0-rc.33.js:10:403654)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: undefined
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0013: │ left-pad@https://github.com/left-pad/left-pad.git#commit=2fca6157fcca165438e0f9495cf0e5a4e6f71349 can't be found in the cache and will be fetched from GitHub
j [HTTPError]: Response code 404 (Not Found)
    at i.<anonymous> (/home/kherock/test/.yarn/releases/yarn-2.0.0-rc.33.js:10:403654)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: undefined
}
➤ YN0000: └ Completed
➤ YN0000: Done in 1.36s
``` 

**Environment if relevant:**

 - OS: Linux (Debian 10)
 - Node version 12.16.3
 - Yarn version 2.0.0-rc.33

**Additional context**

Reverting back to `2.0.0-rc.32` resolves the issue.

### PR DESCRIPTION
**Pull request by paul-soporan**
(Unrelated: I'm still using my fork because I have to clean up a few branches before I change `origin`.)

**What's the problem this PR addresses?**

New style GitHub urls weren't parsed correctly.

Fixes #1317.

**How did you fix it?**

Now the `protocol=` part of `protocol=abcdef` (the "treeish" part of the url) is discarded correctly.

### CODE REVIEW

File: packages/plugin-github/sources/githubUtils.ts [hunk 1]
```diff
@@ -35,7 +35,12 @@ export function parseGithubUrl(urlStr: string): ParsedGithubUrl {
 
   let [, auth, username, reponame, treeish = `master`] = match;
 
-  treeish = treeish.replace(/[^:]*:/, ``);
+  // Replace Treeish Protocol
+  treeish = treeish
+    // New-style: "commit=abcdef" (without the extras)
+    .replace(/[^=]*=/, ``)
+    // Old-style: "commit:abcdef"
+    .replace(/[^:]*:/, ``);
```
Comment (arcanis) [inline packages/plugin-github/sources/githubUtils.ts:43]: It would be sounder to use `querystring.parse` and explicitly extract `commit` (there can be no other field, since the normalization pass turned tags and semvers into commit hashes).

Comment (paul-soporan) [reply packages/plugin-github/sources/githubUtils.ts]: Done. I forgot that all URLs are normalized by the `GitResolver`. 😅

**Comment by paul-soporan** [comment]
Just to make sure I understand: Are GitHub URLs always going to be normalized first so that they include `commit=abcdef` in their `treeish` part? Is the `githubUtils.parseGithubUrl` function supposed to only parse URLs that contain `commit=abcdef`?
If that's the case, all of these tests would have to be updated: https://github.com/yarnpkg/berry/blob/master/packages/plugin-github/tests/githubUtils.test.ts.
If that's not the case, I misunderstood what you've said. 😄

**Comment by arcanis** [comment]
Yeah, those tests didn't change since November, and I think the Git refactoring (with the URL normalization) happened after that. Now the GitHub resolver isn't directly injected into the resolution pipeline - it's called by the Git resolver, which first resolves tags, branches, semver ranges, etc.

**Comment by paul-soporan** [comment]
I made the `parseGithubUrl` function support both old style and new style URLs, to make it more generic. (New style URLs are only guaranteed in the context of the `GithubFetcher`.)

Now it first tries to parse `treeish` using `querystring` and then if it fails it falls back to the old style.

This way we can keep the existing tests. I also added 2 new scenarios for the new style URLs.
