### PR TITLE
fix(core): throw if cache is missing when immutable

### LINKED ISSUE #2776: [Bug] --immutable-cache attempts to create directory
We currently have a set up that mounts our yarn cache mounted read-only into a docker container for building. On yarn 2.1.1, we run with `--immutable-cache`, and everything worked fine. Since updating to 2.4.1, we now get a permission denied error from trying to create the cache dir.

~It seems as though this problem has come from #2383, which changes the behaviour from creating the cache dir when writing a cache file (which would never happen with `--immutable-cache`, to creating it on the creation of the `Cache`, regardless of the state of immutable.~

### PR DESCRIPTION
**Pull request by mrginglymus**
Fixes #2776

### CODE REVIEW

File: packages/yarnpkg-core/sources/Cache.ts [hunk 1]
```diff
@@ -120,15 +120,25 @@ export class Cache {
   }
 
   async setup() {
+    // mkdir may cause write operations even when directories exist. To ensure that the cache can be successfully used
+    // on read-only filesystems, only run mkdir when not running in immutable mode.
```
Comment (arcanis) [inline packages/yarnpkg-core/sources/Cache.ts:124]: Is this comment correct? How can `mkdir` make write operations when the directories exist? Isn't the problem rather than you didn't have the folder, and thus the write operation failed? 🤔

If the comment is correct, perhaps it'd be worth posting it on the Node repo as well along with a repro, that sounds really strange.

Comment (arcanis) [reply packages/yarnpkg-core/sources/Cache.ts:124]: Digging a bit it may be related to the behaviour described here:
https://bug-coreutils.gnu.narkive.com/jKTgWRAO/mkdir-p-and-erofs

Comment (mrginglymus) [reply packages/yarnpkg-core/sources/Cache.ts:124]: I'm going to see if I can put together a minimal repro; certainly `mkdirp()` works where `mkdir(, {recursive: true})` doesn't.

Comment (mrginglymus) [reply packages/yarnpkg-core/sources/Cache.ts:124]: Ah...the critical bit of information I forgot to include is that this is on Windows...

Comment (mrginglymus) [reply packages/yarnpkg-core/sources/Cache.ts:124]: https://github.com/mrginglymus/mkdir-doom <- minimal repro. So it's definitely a node bug, but I would appreciate if this (or similar) workaround could be included in yarn to save me having to patch the offending line.

Comment (mrginglymus) [reply packages/yarnpkg-core/sources/Cache.ts:124]: https://github.com/nodejs/node/issues/38347
