### PR TITLE
Avoid crash in simplifyRanges by removing subsets up front

### LINKED ISSUE #6373: [Bug?]: NodeJS crash when running simplifyRanges
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Too many peer dependency warnings causes yarn to crash during `simplifyRanges`.  Here's the error from NodeJS:

```
#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804 (see crbug.com/1201626)
#
#
#
#FailureMessage Object: 00000077B03FDEA0
----- Native stack trace -----

 1: 00007FF62F716CEB node::SetCppgcReference+18123
 2: 00007FF62F60C57F node::TriggerNodeReport+72847
 3: 00007FF63050D042 V8_Fatal+162
 4: 00007FF62FF7B255 v8::Platform::SystemClockTimeMillis+855861
 5: 00007FF62FDFC3E3 v8::base::Thread::StartSynchronously+1458307
 6: 00007FF62FE1AD83 v8::Message::GetIsolate+15459
 7: 00007FF62FC3C4A3 v8::CodeEvent::GetFunctionName+181699
 8: 00007FF5D015AAFA
```

And here's the callstack immediately before the crash:

```
simplifyRanges (C:\repos\berry\packages\yarnpkg-core\sources\semverUtils.ts:207)
applyVirtualResolutionMutations (C:\repos\berry\packages\yarnpkg-core\sources\Project.ts:2681)
Project.resolveEverything (C:\repos\berry\packages\yarnpkg-core\sources\Project.ts:1028)
processTicksAndRejections (node:internal/process/task_queues:95)
```

### To reproduce

Unfortunately the nature of this bug is that there's no simple repro for it.  I'm hitting it in a large private monorepo.  From debugging, what I see is that `simplifyRanges` is getting called with an array of length 302.  These are ranges of `react`, from packages that depend on it with a very loose version requirement, so most of these entries are rather complex semvers such as `~16.9.0 || ~16.11.0 || ~16.13.1 || ~17.0.1`.

As `simplifyRanges` runs, the `alternatives` array grows excessively — on my system I tracked it up to a size of about 112M elements before it crashed.  (That's if you tell Node to allow Yarn more memory...otherwise it will OOM significantly earlier.)

### Environment

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
  Binaries:
    Node: 20.14.0 - ~\AppData\Local\Temp\xfs-f134b08e\node.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

I'm happy to help with a fix, but not very familiar with the Yarn codebase and it's not clear exactly what the fix is.  If I'm reading it right, this is just for reporting warnings to the user in which case it might be as simple as capping the size of the array — since it's not going to be useful if there are more than a handful of entries, anyway.

### PR DESCRIPTION
**Pull request by smikula**
## What's the problem this PR addresses?

Resolves #6373.  The problem is that `simplifyRanges` doesn't correctly reduce redundant OR ranges.  For example, `~1.0.1 || ~1.0.2` should be simplified to `~1.0.1`.  As the algorithm runs, it will effectively calculate every _combination_ of terms in such ranges.  For example, given two ranges like `~1.0.1 || ~1.0.2`, the `nextAlternatives` array will end up with 2*2 = 4 entries; if you have 100 such ranges you'll end up with 2^100 entries.  Growing exponentially like this it's not hard to crash the process.

Arguably packages should not specify peer deps with this sort of redundant range, but sometimes they do (I'm working on cleaning up my project now that I know what the problem is!)  Regardless, yarn shouldn't crash when it happens.

## How did you fix it?

At the beginning of `simplifyRanges`, I reduce any range of this sort by splitting it apart and using `sember.subset` to check if one part of the range is a subset of another, in which case it can be excluded from the simplified range.  I short circuit if the range only has one term, to avoid any excess parsing.

I think this is the right fix, but I'm happy to take feedback or hand it off if someone knows better.  (Maybe @arcanis as author of this code?)

## Checklist

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

File: packages/yarnpkg-core/sources/semverUtils.ts [hunk 1]
```diff
@@ -204,7 +204,7 @@ export function stringifyComparator(comparator: Comparator) {
 }
 
 export function simplifyRanges(ranges: Array<string>) {
-  const parsedRanges = ranges.map(range => validRange(range)!.set.map(comparators => comparators.map(comparator => getComparator(comparator))));
+  const parsedRanges = ranges.map(removeSubsets).map(range => validRange(range)!.set.map(comparators => comparators.map(comparator => getComparator(comparator))));
```
Comment (arcanis) [inline packages/yarnpkg-core/sources/semverUtils.ts:207]: Can we rather do a `filter` on the `set` after we already parsed it, rather than the hardcoded `||` split followed by `semver.subset` calls (to avoid parsing the ranges twice)?

File: packages/yarnpkg-core/tests/semverUtils.test.ts [hunk 2]
```diff
@@ -112,6 +112,8 @@ describe(`semverUtils`, () => {
       [[`<=1.5.3`, `1.5.3`], `1.5.3`],
       [[`1.5.3`, `1.5.3`], `1.5.3`],
       [[`1.5.0`, `1.5.3`], null],
+      [[`~1.0.1 || ~1.0.2`], `~1.0.1`],
+      [[`~1.0.1 || ~1.0.2`, `~1.0.1 || ~1.0.2`], `~1.0.1`],
```
Comment (arcanis) [inline packages/yarnpkg-core/tests/semverUtils.test.ts:116]: Can you add a test that crashes the process (for example perhaps something like:
```suggestion
      [[`~1.0.1 || ~1.0.2`, `~1.0.1 || ~1.0.2`], `~1.0.1`],
      [[`1.0.0${` || 1.0.0`.repeat(1000)}`], `~1.0.1`],
```

Comment (smikula) [reply packages/yarnpkg-core/tests/semverUtils.test.ts:116]: Sure, I added this.

File: packages/yarnpkg-core/sources/semverUtils.ts (hunk 1 above)
Comment (smikula) [reply packages/yarnpkg-core/sources/semverUtils.ts:207]: I considered this, but `semver.subset` only accepts a `string` or a `Range` object.  If I have the parsed range, then I need to compare the members of `Range.set` that look like:

```
[
  [
    Comparator {
      options: {},
      loose: false,
      operator: '>=',
      semver: [SemVer],
      value: '>=1.0.1'
    },
    Comparator {
      options: {},
      loose: false,
      operator: '<',
      semver: [SemVer],
      value: '<1.1.0-0'
    }
  ],
  [
    Comparator {
      options: {},
      loose: false,
      operator: '>=',
      semver: [SemVer],
      value: '>=1.0.2'
    },
    Comparator {
      options: {},
      loose: false,
      operator: '<',
      semver: [SemVer],
      value: '<1.1.0-0'
    }
  ]
]
```

So then I need to either:
- Implement my own version of `subset` (yuck), or...
- Reconstruct a proper range out of the above without any more parsing, which really gets into the guts of `semver`

Either case seems like it would add a lot of complexity for marginal benefit.  Given that I already short-circuit on ranges that don't have `||`, I'm expecting the extra cost here is pretty minimal.

What do you think?

**Comment by smikula** [comment]
@arcanis Any further thoughts here?

**Comment by arcanis** [comment]
Looks good to me, thanks!
