### PR TITLE
fix(shell): make some errors recoverable

### LINKED ISSUE #1984: [Bug] Yarn Shell rm -rf crashes instead of returning a non-zero code
- [x] I'd be willing to implement a fix

**Describe the bug**

```
{
  "scripts": {
    "all:clean2": "rm -rf ./packages/*/*/lib || echo ok"
  }
}
```

When no files match `./packages/*/*/lib` it should still `echo ok`. But it does not.

**To Reproduce**

Clone https://github.com/sterblue/labs

Then `yarn install` and `yarn all:clean2`

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

The shell didn't have any concept of recoverable errors, which meant that commands like `echo inexistentFolder/* || true` were throwing instead of printing to stderr and continuing on to the next command in the chain.

Fixes #1984.

**How did you fix it?**

I've created a new `ShellError` class with a `recoverable` property. When executing a command chain, we now check if a recoverable error is thrown and we don't crash in that case - we instead print the error message to stderr and set the exit code to 1, so that we can continue on to the next command in the chain. I've also made a few more errors recoverable (`Bad file descriptor`, `Unbound {variable, argument}`).

**Checklist**

- [X] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [X] I have set the packages that need to be released for my changes to be effective.

- [X] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

File: packages/yarnpkg-shell/sources/errors.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+export type ShellErrorOptions = {
+  recoverable: boolean;
+};
+
+export class ShellError extends Error {
+  public recoverable: boolean;
```
Comment (arcanis) [inline packages/yarnpkg-shell/sources/errors.ts:6]: Why not just keep using the regular `Error` class for unrecoverable errors, instead of keeping a `recoverable` flag?

Comment (paul-soporan) [reply packages/yarnpkg-shell/sources/errors.ts:6]: Because I wanted shell errors to have a `ShellError` name instead of just `Error`. Do you think it makes sense or should I remove it?

Comment (arcanis) [reply packages/yarnpkg-shell/sources/errors.ts:6]: Hm .. I'd say that imo the extra complexity isn't worth it 🤔

Comment (paul-soporan) [reply packages/yarnpkg-shell/sources/errors.ts:6]: Makes sense! I'll change it 👍
