### PR TITLE
fix(plugin-workspace-tools): Remove scripts from workspaces during focus

### LINKED ISSUE #1690: [Bug] self-reference links should not be created for unfocused workspaces
**Describe the bug**

The self-reference links (with `nodeLinker: node-modules`) are created even if the workspace is not focused.

**To Reproduce**

<details>
  <summary>Reproduction</summary>

  ```js repro
  const fs = require('fs')

  fs.writeFileSync('.yarnrc.yml', 'nodeLinker: node-modules')

  await packageJson({ name: 'root', workspaces: ['packages/*'] })
  await packageJson({ name: 'package-a' }, { cwd: 'packages/package-a' })
  await packageJson({ name: 'package-b' }, { cwd: 'packages/package-b' })
  await yarn('workspaces', 'focus', 'package-a')

  expect(fs.existsSync('node_modules/package-b')).toBe(false)
  ```
</details>

**Environment**

 - Yarn version 2.1.1

**Additional context**

The usecase is that I'd like to create some internal `@types` workspaces that depends on some external type packages, it works fine if we did a full installation, but the external type packages won't exist if we did a `yarn workspaces focus` install that does not involve this internal `@types` workspace. And TypeScript always checks all the `@types` packages before doing the actual type-checking, which includes checking this unfocused internal `@types` workspace since its self-reference link is still created, and TypeScript will always throw "module not found" errors since its external type dependencies are not installed.

### PR DESCRIPTION
**Pull request by Embraser01**
**What's the problem this PR addresses?**

~unspecified workspaces were not removed from the project during focus install. Unspecified workspaces were kept inside `node_modules` and so, was accessible by others.~

This PR fixes the `yarn workspaces focus <workspace>` command. `postinstall` scripts from unfocus workspaces were executed.

**How did you fix it?**

We clear scripts from unfocused workspaces manifests.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by Embraser01** [comment]
Converitng to draft as it seems to throw an error when using yarn after
image

File: packages/yarnpkg-core/sources/Project.ts [hunk 1]
```diff
@@ -1111,9 +1111,11 @@ export class Project {
 
       const fetchResult = await fetcher.fetch(pkg, fetcherOptions);
 
-      if (this.tryWorkspaceByLocator(pkg) !== null) {
+      const workspace = this.tryWorkspaceByLocator(pkg);
+
+      if (workspace !== null) {
         const buildScripts: Array<BuildDirective> = [];
-        const {scripts} = await Manifest.find(fetchResult.prefixPath, {baseFs: fetchResult.packageFs});
+        const {scripts} = await workspace.manifest;
```
Comment (merceyz) [inline packages/yarnpkg-core/sources/Project.ts:1118]:
```suggestion
        const {scripts} = workspace.manifest;
```

File: packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/focus.test.js [hunk 2]
```diff
@@ -138,19 +138,49 @@ describe(`Commands`, () => {
...
+
+          await run(`install`);
+
+          await xfs.removePromise(ppath.join(path, `.yarn/cache`));
+          await xfs.removePromise(ppath.join(path, `.yarn/build-state.yml`));
+
+          const fooPostinstallPath = ppath.join(path, `packages/foo/postinstall.log`);
+          const quxPostinstallPath = ppath.join(path, `packages/qux/postinstall.log`);
+          await xfs.removePromise(fooPostinstallPath);
+          await xfs.removePromise(quxPostinstallPath);
```
Comment (arcanis) [inline packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/focus.test.js:160]: Are those lines necessary? Can't we just run the focus as first command?

Comment (Embraser01) [reply packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/focus.test.js:160]: :+1: I'll remove them
