### PR TITLE
fix(core): fix empty scripts

### LINKED ISSUE #1071: [Bug] Packages with an empty string postinstall script fail
- [x] I'd be willing to implement a fix

**Describe the bug**

At least one NPM package (`async-lock@1.1.3`, removed in a later version) has the line `"postinstall": ""` in its package.json. NPM and Yarn v1 accept this silently, but Yarn v2 fails.

**To Reproduce**

```js repro
await expect(
  packageJsonAndInstall({ dependencies: { "async-lock": "1.1.3" } })
).resolves.toEqual(expect.anything())
```

**Screenshots**

```
$ yarn
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0.2s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.76s
➤ YN0000: ┌ Link step
➤ YN0007: │ async-lock@npm:1.1.3 must be built because it never did before or the last one failed
➤ YN0009: │ async-lock@npm:1.1.3 couldn't be built successfully (exit code undefined, logs can be found here: /private/var/folders/48/4qjy_0q122zf0xxr3y0m87w00000gn/T/xfs-5251d6aa/build.log)
➤ YN0009: │ async-lock@npm:1.1.3 couldn't be built successfully (exit code undefined, logs can be found here: /private/var/folders/48/4qjy_0q122zf0xxr3y0m87w00000gn/T/xfs-5251d6aa/build.log)
➤ YN0000: └ Completed in 1.54s
➤ YN0000: Failed with errors in 2.57s
```

**Environment if relevant (please complete the following information):**

- OS: macOS
- Node version v13.11.0
- Yarn version 2.0.0-rc.30

### PR DESCRIPTION
**Pull request by paul-soporan**
**What's the problem this PR addresses?**

Empty scripts in `executePackageScript` were failing because the comparision didn't include only `undefined`, but it also included the empty string.

Fixes #1071.

**How did you fix it?**

I changed `if (!script) return;` to `if (typeof script === 'undefined') return;`.

I also added an integration test.

### CODE REVIEW

**Comment by arcanis** [comment]
The original code looked fine (don't execute empty strings), are you sure that's the right fix? 🤔

File: packages/yarnpkg-core/sources/scriptUtils.ts [hunk 1]
```diff
@@ -272,7 +272,7 @@ export async function executePackageScript(locator: Locator, scriptName: string,
     const {manifest, env, cwd: realCwd} = await initializePackageEnvironment(locator, {project, binFolder, cwd, lifecycleScript: scriptName});
 
     const script = manifest.scripts.get(scriptName);
-    if (!script)
+    if (typeof script === `undefined`)
       return;
```
Comment (arcanis) [inline packages/yarnpkg-core/sources/scriptUtils.ts:276]: I think it might rather be this:
```suggestion
    if (!script)
      return 0;
```

Comment (paul-soporan) [reply packages/yarnpkg-core/sources/scriptUtils.ts:276]: Makes more sense not to execute an empty string, but I don't think we should return exit code 0 if the manifest doesn't have the specified script. 🤔

Comment (arcanis) [reply packages/yarnpkg-core/sources/scriptUtils.ts:276]: Thinking more, I think you're right. I have a monitoring plugin tracking the scripts that execute on my project, and I'd probably consider it a bug if empty ones weren't reported. Good thinking 👍

That being said, there's still a bug somewhere: the `exitCode` variable in `Project.ts` should be typed as `number`, which would have allowed us to catch this problem earlier. Can you make the fix in the same PR? I wonder if there's a lint rule that could prevent variable declarations that are missing both explicit and inferred types 🤔

Comment (paul-soporan) [reply packages/yarnpkg-core/sources/scriptUtils.ts]: There's [`explicit-function-return-type`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) in `@typescript-eslint/eslint-plugin` that can prevent this kind of errors, but it requires always annotating the return type. I'd personally enable it, it's even part of their recommended config. Most importantly, it makes us think twice before annotating the return type. What do you think?

Comment (arcanis) [reply packages/yarnpkg-core/sources/scriptUtils.ts]: I meant [this code](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-core/sources/Project.ts#L1319-L1328). Since the `exitCode` declaration doesn't have explicit type, nor initializer, TS silently types it as `any`, which allowed `undefined` to be returned. Maybe [`no-unsafe-assignment`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unsafe-assignment.md)?

I don't have strong opinions on explicit function return types, except it would probably require a bunch of tedious changes 🤔 Maybe it'd be simpler to just ban functions from mixing returns with and without values, which is easy to do with [`consistent-return`](consistent-return).
