### PR TITLE
fix(set version) - fix build workflow for windows

### LINKED ISSUE #5670: [Bug?]: `yarn set version from sources` cannot update on Windows
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When I want to update by `yarn set version from sources` - apparently from a version later than https://github.com/yarnpkg/berry/commit/200e84d83aa0107d4b9b2f32387bf770187c80da, it fails on Windows due to missing binary 'mv':

➤ YN0001: Error: spawn mv ENOENT

AFAICT, this is caused by changes in buildWorkflow (packages/plugin-essentials/sources/commands/set/version/sources.ts)

### To reproduce

```
yarn set version berry
yarn set version from sources
yarn set version from sources
```

### Environment

```shell
yarn dlx -q envinfo --preset jest

  System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 18.17.1 - ~\AppData\Local\Temp\xfs-840ad713\node.CMD
    Yarn: 4.0.0-rc.49.git.20230817.hash-27a673d - ~\AppData\Local\Temp\xfs-840ad713\yarn.CMD
    npm: 9.8.0 - c:\tools\nodejs\npm.CMD
    pnpm: 7.26.2 - ~\AppData\Roaming\npm\pnpm.CMD
```

### Additional context

Current workaround until fix is to always reset version to stable.

### PR DESCRIPTION
**Pull request by x318**
**What's the problem this PR addresses?**

 Resolves #5670 

...

**How did you fix it?**

Use windows-native `move` command for win32` platform
...

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

File: packages/plugin-essentials/sources/commands/set/version/sources.ts [hunk 1]
```diff
@@ -33,7 +34,7 @@ const updateWorkflow = ({branch}: {branch: string}) => [
 
 const buildWorkflow = ({plugins, noMinify}: {noMinify: boolean, plugins: Array<string>}, output: PortablePath, target: PortablePath) => [
   [`yarn`, `build:cli`, ...new Array<string>().concat(...plugins.map(plugin => [`--plugin`, ppath.resolve(target, plugin as Filename)])), ...noMinify ? [`--no-minify`] : [], `|`],
-  [`mv`, `packages/yarnpkg-cli/bundles/yarn.js`, npath.fromPortablePath(output), `|`],
+  [IS_WIN32 ? `move` : `mv`, `packages/yarnpkg-cli/bundles/yarn.js`, npath.fromPortablePath(output), `|`],
```
Comment (x318) [inline packages/plugin-essentials/sources/commands/set/version/sources.ts:37]: Ideally, it would be worth making some kind of mechanism for platform-specific commands, but this should work
