### PR TITLE
fix(essentials): make `--mode=update-lockfile` disable immutable installs

### LINKED ISSUE #3606: [Bug?]: installation with mode=update-lockfile should success regardless the enableImmutableInstalls config
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

On the CI, the `--mode=update-lockfile` option is used to intend to update the lockfile, but it fails with an error code due to the `enableImmutableInstalls=true`

### To reproduce

Try to automate lockfile update on github action like:

https://github.com/cometkim/yarn-changeset-action/blob/9def36cc79/src/run.ts#L202-L203

running `await exec("yarn", ["config", "set", "enableImmutableInstalls", "false"], { cwd });` before install gonna fix the issue, but it changes yarnrc unnecessarily.

### Environment

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
  Binaries:
    Node: 16.11.0 - /tmp/xfs-9cfba581/node
    Yarn: 3.0.2 - /tmp/xfs-9cfba581/yarn
    npm: 8.0.0 - ~/.asdf/installs/nodejs/16.11.0/bin/npm
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cometkim**
**What's the problem this PR addresses?**

Resolves #3606

**How did you fix it?**

`--mode=update-lockfile` means that the user has explicitly expected "dependency update mode".

This should take precedence over immutable mode, which is automatically set in the CI environment.

This change disables all immutable flag behaviors in the update mode.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Review by merceyz — CHANGES_REQUESTED** [review]
In that case explicitly specifying both `--immutable` and `--mode="update-lockfile"` should probably throw.

This also needs a test, could you add one to https://github.com/yarnpkg/berry/blob/a66ee4be30d69586a651dabee0f6a8781dd5da9f/packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js ?

File: packages/plugin-essentials/sources/commands/install.ts [hunk 1]
```diff
@@ -218,7 +218,11 @@ export default class YarnCommand extends BaseCommand {
       }
     }
 
-    const immutable = this.immutable ?? configuration.get(`enableImmutableInstalls`);
+    const updateMode = this.mode === InstallMode.UpdateLockfile;
+    if (updateMode && (this.immutable || this.immutableCache))
+      throw new UsageError(`\`--immutable\` and \`--immutable-cache\` cannot be used with \`--mode=update-lockfile\``);
```
Comment (paul-soporan) [inline packages/plugin-essentials/sources/commands/install.ts:223]: Instead of wrapping in backticks it would be more useful to use colors: `formatUtils.pretty(configuration, value, formatUtils.Type.CODE)`.

File: packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js [hunk 2]
```diff
@@ -397,5 +397,37 @@ describe(`Commands`, () => {
...
+      }, async ({path, run}) => {
+        await xfs.writeFilePromise(`${path}/${Filename.rc}`, `enableImmutableInstalls: true`);
+
+        const {stdout} = await run(`install`, `--mode=update-lockfile`);
+        expect(stdout).not.toMatch(/YN0028/g);
+      }),
+    );
+
+    test(
+      `it should throw when \`--immutable\` or \`--immutable-cache\` specified with \`--mode=update-lockfile\``,
```
Comment (paul-soporan) [inline packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js:416]:
```suggestion
      `it should throw when \`--immutable\` or \`--immutable-cache\` is specified with \`--mode=update-lockfile\``,
```

File: packages/plugin-essentials/sources/commands/install.ts [hunk 3]
```diff
@@ -291,7 +295,7 @@ export default class YarnCommand extends BaseCommand {
     }
 
     const {project, workspace} = await Project.find(configuration, this.context.cwd);
-    const cache = await Cache.find(configuration, {immutable: this.immutableCache, check: this.checkCache});
+    const cache = await Cache.find(configuration, {immutable: this.immutableCache && !updateMode, check: this.checkCache});
```
Comment (paul-soporan) [inline packages/plugin-essentials/sources/commands/install.ts:298]: Small nit: I think it would be better to extract the `immutable` property of the `Cache.find` parameter next to the `immutable` declaration:
```ts
const immutable = ...;
const immutableCache = this.immutableCache && !updateMode;
```

**Review by paul-soporan — DISMISSED** [review]

**Comment by arcanis** [comment]
Looks good, thanks!
