### PR TITLE
fix(pnp): esm - resolve relative imports with search params

### LINKED ISSUE #3894: [Bug?]: Dynamic import of module with query string param doesn't work
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

When I enable the `pnpEnableEsmLoader` flag & try to import local module in this manner:

```javascript
import('./module.js?cache=busted');
```

I get errors such as these (real path prefixes replaced):

```
/path/to/.pnp.cjs:46662
  return Object.defineProperties(new Error(message), {
                                 ^

Error: Qualified path resolution failed - none of those files can be found on the disk.

Source path: /path/to/module.js?cache=busted
Not found: /path/to/module.js?cache=busted

    at internalTools_makeError (/path/to/.pnp.cjs:46662:34)
    at resolveUnqualified (/path/to/.pnp.cjs:48025:13)
    at resolveRequest (/path/to/.pnp.cjs:48058:14)
    at Object.resolveRequest (/path/to/.pnp.cjs:48130:26)
    at resolve$1 (file:///path/to/.pnp.loader.mjs:206:25)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ESMLoader.import (node:internal/modules/esm/loader:276:22)
    at importModuleDynamically (node:internal/modules/esm/translators:111:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
```

-------------------------------------------------------------

The whole reason behind doing this is that [described here](https://ar.al/2021/02/22/cache-busting-in-node.js-dynamic-esm-imports/) (tl;dr: CommonJS allows you to manipulate its import cache, but ES-modules don't have that any more)

### To reproduce

**Minimal repro** is a rather esoteric concept at this stage & I do believe that this is a question of such imports even being supported by yarn.

If it is indeed supported, and you believe that this should work as is, I will gladly supply more information as requested.

### Environment

```shell
System:
    OS: Linux 5.11 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 16.13.1 - /tmp/xfs-3cc39734/node
    Yarn: 3.2.0-rc.5 - /tmp/xfs-3cc39734/yarn
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

- Relative imports containing search parameters doesn't work.
- Cache busting doesn't work

Fixes #3894

**How did you fix it?**

- If the specifier is relative use the `parentURL` as the base in the `URL` constructor
- Preserve `search` and `hash` in the resolve result

**Checklist**
- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x] I have set the packages that need to be released for my changes to be effective.
- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

File: packages/yarnpkg-pnp/sources/esm-loader/hooks/resolve.ts [hunk 1]
```diff
@@ -18,12 +19,12 @@ export async function resolve(
     return defaultResolver(originalSpecifier, context, defaultResolver);
 
   let specifier = originalSpecifier;
-  const url = loaderUtils.tryParseURL(specifier);
+  const url = loaderUtils.tryParseURL(specifier, isRelativeRegexp.test(specifier) ? context.parentURL : undefined);
```
Comment (arcanis) [inline packages/yarnpkg-pnp/sources/esm-loader/hooks/resolve.ts:22]: Wouldn't it work to always specify the parent URL, even for absolute URLs?

Comment (merceyz) [reply packages/yarnpkg-pnp/sources/esm-loader/hooks/resolve.ts:22]: For absolute URLs it would just be ignored but for package names it would incorrectly resolve to a file
```js
console.log(new URL('no-deps', import.meta.url).href);
// file:///C:/berry/no-deps
```

**Comment by kubijo** [comment]
Hey guys!

We have a pending MR in our project for migration of build tooling from CJS to ES, and this fix in the upstream version of Yarn is the last bit that is holding it from merge.

Do you have an idea whether you'll get to merge this soon-ish?
I am fine with `from sources` version of yarn, but branch version is a tad too far for my taste :)

**Comment by arcanis** [comment]
It's currently the holidays so it'll have to wait a lil' bit before I get to the review queue 🙂
