### PR TITLE
fix(pnpm): pnpm linker no longer removes node_modules when nm linker is active

### LINKED ISSUE #4160: [Bug?]: Adding a portal from a package outside a workspace to one inside fails in 3.2.0
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

I have the following package structure:
* `some-workspace`
  * `foo`
  * `bar`
* `baz`

The dependencies of these packages are as such:
* `some-workspace` has a `workspaces` key listing `foo` and `bar`
* `bar` has a `dependencies` entry for `"foo": "workspace:*"`
* `baz` has a `dependencies` entry for `"bar": "portal:../some-workspace/bar"`
* `baz` has a `resolutions` entry for `"bar/foo": "portal:../some-workspace/foo"`

Up to Yarn v3.1.1, this setup worked fine - no errors, no real funkiness.

With Yarn v3.2.0, when I run `yarn install` inside `baz`, I'm now seeing an error occur with this kind of setup, along these lines:
```
➤ YN0001: │ Error: Assertion failed: Writing attempt prevented to /some-workspace/bar/node_modules/foo which is outside project root: /baz
```

### To reproduce

I've created a reproduction here: https://github.com/spiltcoffee/yarn-workspace-portal-issue

### Environment

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 16.13.2 - C:\Temp\xfs-82221d88\node.CMD
    Yarn: 3.2.0 - C:\Temp\xfs-82221d88\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
```

### Additional context

I've also tried the following in an attempt to fix the issue:
* Adding a dependency on `foo` that has the same `portal:`
* Adding a `packageExtensions` key to the `.yarnrc.yml`
* Updated to `canary` (it appears to just be Yarn v3.2.0 at the moment anyway?)

### LINKED ISSUE #4172: [Bug] Yarn instal fails if node_modules is a docker volume or similar
This is the exact same issue as #1184.

When using nodeLinker: node-modules, during the link step, yarn will attempt to delete the entire node_modules directory, instead of only its contents. This causes problems with the common docker pattern of mounting node_modules as a volume, resulting in an error like the following:

```
➤ YN0000: ┌ Link step
➤ YN0001: │ Error: EBUSY: resource busy or locked, rmdir '/work/node_modules'
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 98ms
```

### To reproduce

```
git clone git@github.com:ncjones/yarn-nm-volume.git
cd yarn-nm-volume
docker compose run script yarn install
```

See [ncjones/yarn-nm-volume](https://github.com/ncjones/yarn-nm-volume).

### Environment

```shell
System:
    OS: macOS
```

### PR DESCRIPTION
**Pull request by larixer**
**What's the problem this PR addresses?**

The pnpm linker attempts to delete `node_modules` directory all the time, this causes install failure when Yarn has no permissions. This problem happens even when `node-modules` linker is active.

Fixes #4172
Fixes #4160

**How did you fix it?**

Based on the evaluation of pnpm linker finalizeInstall code, seems this behavior - to manipulate node_modules directory- was not intended. I have updated it so that this code was not run.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

File: packages/plugin-pnpm/sources/PnpmLinker.ts [hunk 1]
```diff
@@ -274,10 +274,11 @@ class PnpmInstaller implements Installer {
     }
 
     // Wait for the package installs to catch up
-    await this.asyncActions.wait(),
+    await this.asyncActions.wait();
```
Comment (arcanis) [inline packages/plugin-pnpm/sources/PnpmLinker.ts:277]: Was this the reason for the flaky test? 🤯

**Review by arcanis — APPROVED** [review]
I feel like it'd be better if the pnpm linker could have no knowledge of other linkers, but that would require a better cleaning mechanism 🤔 fine to merge as is
