### PR TITLE
fix(nm): Downgrades `nmMode: hardlinks-global` if cross-device usage detected

### LINKED ISSUE #3187: [Bug?]: `yarn dlx` breaks with hardlinked node modules
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

`yarn dlx` breaks when `nmMode` is set to `hardlinks-[local/global]`

### To reproduce

```js repro
await yarn('init', '-y');
await yarn('config', 'set', 'enableGlobalCache', 'true');
await yarn('config', 'set', 'nodeLinker', 'node-modules');
await yarn('config', 'set', 'nmMode', 'hardlinks-global');

await expect(yarn('dlx', 'sirv-cli', '-v')).rejects.not.toThrow();
```

### Environment

  System:
    OS: Linux 5.12 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  Binaries:
    Node: 16.5.0 - /tmp/xfs-c1cde8a3/node
    Yarn: 3.0.0 - /tmp/xfs-c1cde8a3/yarn
    npm: 7.20.0 - ~/.local/npm-global/bin/npm

### LINKED ISSUE #3191: [Bug?]: yarn errors with `hardlinks-global` and a global cache on a different device
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

**Issue**: When the global cache is located on a different device, yarn errors out.

(This will occur invariably in GitHub Actions for projects using yarn v3.)

I would suggest that yarn should gracefully fall back to `hardlinks-local` or `classic`. Otherwise, in the case of multiple contributors to a repository (or CI usage), this would effectively force `nmMode` to be set to the lowest common denominator.

### To reproduce

- **[Reproduction](https://github.com/danielroe/yarn3-windows)**
- **[GitHub Action run](https://github.com/danielroe/yarn3-windows/runs/3176103012)**

### Environment

```
  System:
    OS: Windows 10 10.0.17763
    CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
  Binaries:
    Node: 14.17.3 - C:\Users\RUNNER~1\AppData\Local\Temp\xfs-74bccc19\node.CMD
    Yarn: 3.0.0 - C:\Users\RUNNER~1\AppData\Local\Temp\xfs-74bccc19\yarn.CMD
    npm: 6.14.13 - C:\hostedtoolcache\windows\node\14.17.3\x64\npm.CMD
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by larixer**
**What's the problem this PR addresses?**

When `hardlinks-global` is used for the case when global cache and install folder are on different devices install aborts now, because hardlinks cannot be used across different devices. 

Closes #3187
Closes #3191

**How did you fix it?**

We check now for the cross-device hardlink creation error and automatically downgrade `nmMode` to `hardlinks-local`, install continues normally. At the end of install we warn the user and provide mitigation steps in the linked documentation on our website.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

File: packages/plugin-nm/sources/NodeModulesLinker.ts [hunk 1]
```diff
@@ -500,6 +500,8 @@ async function findInstallState(project: Project, {unrollAliases = false}: {unro
 }
 
 const removeDir = async (dir: PortablePath, options: {contentsOnly: boolean, innerLoop?: boolean}): Promise<any> => {
+  console.log(`removeDir`, dir);
+  console.trace();
```
Comment (merceyz) [inline packages/plugin-nm/sources/NodeModulesLinker.ts:504]:
```suggestion
```

**Review by merceyz — COMMENTED** [review]
Excellent 👍

File: packages/plugin-nm/sources/NodeModulesLinker.ts (hunk 1 above)
Comment (larixer) [reply packages/plugin-nm/sources/NodeModulesLinker.ts]: Oops, thank you @merceyz !

**Review by merceyz — APPROVED** [review]
