### PR TITLE
fix(core): `--immutable` covers Project.persist

### LINKED ISSUE #2699: [Bug] Even when `immutablePatterns` includes package.json, `--immutable` does not prevent writes to package.json
- [x] I'd be willing to implement a fix

**Describe the bug**

Yarn reformats package.json.  `yarn install --immutable` with `--immutablePatterns: ['package.json']` does not work with this reformatting: package.jsons are reformatted regardless.

For the same reason we'd like `--immutable` to apply to the lockfile, we'd like to apply it to package.json:  while yarn's package.json reformatting should not change semantics, it can result in situations where developers commit files that are guaranteed to be modified when other users pull in those changes and `yarn install`.  CI should be able to enforce that package.json files are canonically formatted.

**To Reproduce**

<details>
  <summary>Reproduction</summary>

  ```js repro
const fs = require('fs');

// create lockfile so that we can use --immutable later
await packageJson({
    dependencies: {
        // alphabetized.
        lodash: '*',  
        react: '*',
    }
})
await yarn(`install`);

// Specify that package.json is immutable, and make dependencies not-alphabetized but still equivalent to the previous
await fs.promises.writeFile('.yarnrc.yml', 
`immutablePatterns:
  - 'package.json'
`
);
await packageJson({
    dependencies: {
        // not alphabetized.
        react: '*',
        lodash: '*',
    }
})
await expect(yarn(`install`, `--immutable`)).rejects.toThrow(`The checksum for package.json has been modified by this install, which is explicitly forbidden.`);
  ```
</details>

### PR DESCRIPTION
**Pull request by isker**
Fixes #2699

**What's the problem this PR addresses?**
`immutablePatterns` cannot cover `package.json`.

**How did you fix it?**
Create `before` hashes before persisting the project.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

**Comment by isker** [comment]
Alternatively I can move the `persist` call into the timed Link step.  Please let me know if you'd prefer that.

File: packages/yarnpkg-core/sources/Project.ts [hunk 1]
```diff
@@ -1414,30 +1414,30 @@ export class Project {
...
-      for (let t = 0; t < immutablePatterns.length; ++t) {
-        if (before[t] !== after[t]) {
-          opts.report.reportError(MessageName.FROZEN_ARTIFACT_EXCEPTION, `The checksum for ${immutablePatterns[t]} has been modified by this install, which is explicitly forbidden.`);
-        }
+    for (let t = 0; t < immutablePatterns.length; ++t) {
+      if (before[t] !== after[t]) {
+        opts.report.reportError(MessageName.FROZEN_ARTIFACT_EXCEPTION, `The checksum for ${immutablePatterns[t]} has been modified by this install, which is explicitly forbidden.`);
       }
-    });
+    }
```
Comment (arcanis) [inline packages/yarnpkg-core/sources/Project.ts:1440]: This part should remain within the link step, otherwise the output will be messy.

**Comment by arcanis** [comment]
Perfect, thanks!

File: packages/acceptance-tests/pkg-tests-specs/sources/features/immutablePatterns.test.ts [hunk 2]
```diff
@@ -123,6 +123,24 @@ describe(`Features`, () => {
       )
     );
 
+    it(`should prevent reformatting of manifests when so configured`,
+      makeTemporaryEnv(
+        {
+        },
+        {
+          nodeLinker: `node-modules`,
```
Comment (larixer) [inline packages/acceptance-tests/pkg-tests-specs/sources/features/immutablePatterns.test.ts:131]: I wonder is setting `nodeLinker` really needed here?

Comment (isker) [reply packages/acceptance-tests/pkg-tests-specs/sources/features/immutablePatterns.test.ts:131]: I was simply cargo culting the other tests in this file.

Comment (isker) [reply packages/acceptance-tests/pkg-tests-specs/sources/features/immutablePatterns.test.ts:131]: No, I don't think it is.  I think I copy-pasted this from my reproduction which was using this linker just because that's what I'm familiar with.

Comment (isker) [reply packages/acceptance-tests/pkg-tests-specs/sources/features/immutablePatterns.test.ts:131]: Or, I copy-pasted it from other tests in this file mindlessly.
