### PR TITLE
Reverts the INIT_CWD change

### LINKED ISSUE #5750: [Bug?]: Breaking change in v4 - `yarn workspace(s)` and `$INIT_CWD`
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

In v2 and v3 using `$INIT_CWD` in global scripts allowed the scripts to enter the workspace that initiated them.

```json
{
  "scripts": {
    "g:build": "cd $INIT_CWD && ...",
    "g:pwd": "echo $INIT_CWD"
  }
}
```

This is still the case if you manually change into the directory of a workspace and call the global script from there.

Doing this using `yarn workspace [name of workspace] g:pwd` however, no longer works the same in v4.
In v2 and v3 it would print the path to the workspace specified in the call to `yarn workspace`.
In v4 it instead prints the path from which the `yarn workspace` call originated (CWD).

I couldn't find it on the list of breaking changes for v4, so I'm not sure if it is intentional.
For me at least the change is unfortunate, since I can no longer reuse global scripts in `yarn workspaces foreach` to do something in each workspace directory. Since the CWD for global scripts is the directory in which the script was defined, there seemingly no longer is a way to get to the directory of the workspace from which the global script was called.

By the way, the link to Sherlock in the GitHub issue template doesn't seem to work at the moment. I had to use archive.org to find a working version of the documentation, and even then the playground didn't work with a 500 Internal Server Error.
I luckilly managed to get it working offline.

### To reproduce

```js repro
await packageJson({
  name: "root",
  scripts: {
      "g:pwd": "pwd && echo $INIT_CWD"
  },
  workspaces: [
    "libs/*"
  ],
});

await packageJson({
  name: "demo"
}, { cwd: "./libs/demo" });

await yarn();

const rootPwd = await yarn("exec", "pwd");
const demoPwd = await yarn("workspace", "demo", "exec", "pwd");

expect(demoPwd).not.toEqual(rootPwd);

const singleWorkspace = await yarn("workspace", "demo", "g:pwd");
expect(singleWorkspace).toEqual(rootPwd + demoPwd);

const multipleWorkspaces = await yarn("workspaces", "foreach", "--all", "run", "g:pwd");
expect(multipleWorkspaces).toContain(rootPwd + rootPwd + rootPwd + demoPwd); // Ignore "Done in Xs Yms" on the last line
```

### Environment

```shell
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 18.16.1 - /private/var/folders/jr/f0flt_ds0rzfc_g50cm8jbfc0000gn/T/xfs-4e01b59a/node
    Yarn: 4.0.0-rc.51 - /private/var/folders/jr/f0flt_ds0rzfc_g50cm8jbfc0000gn/T/xfs-4e01b59a/yarn
    npm: 9.5.1 - ~/.volta/tools/image/node/18.16.1/bin/npm
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by arcanis**
**What's the problem this PR addresses?**

The changes in #4817 caused some breakages in how our users had setup their scripts. While it can be argued that the current behaviour is better by some measures, I'd prefer to avoid breaking anything, especially since it's not very well documented (and/or understood) what's the semantic of INIT_CWD when used with `yarn workspace`, `yarn workspaces foreach`, and global scripts.

Fixes #5750

**How did you fix it?**

I reverted #4817. I'll do a separate semver-minor PR to add extra environment variables with better semantic than INIT_CWD, but that will be in a second time.

**Checklist**

- [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).

- [x] I have set the packages that need to be released for my changes to be effective.

- [x] I will check that all automated PR checks pass before the PR gets reviewed.

### CODE REVIEW

File: packages/yarnpkg-core/sources/scriptUtils.ts [hunk 1]
```diff
@@ -66,15 +66,13 @@ export async function detectPackageManager(location: PortablePath): Promise<Pack
...
-
+        }
         case `npm`: {
           return {packageManagerField: true, packageManager: PackageManager.Npm, reason};
-        } break;
-
+        }
         case `pnpm`: {
           return {packageManagerField: true, packageManager: PackageManager.Pnpm, reason};
-        } break;
```
Comment (arcanis) [inline packages/yarnpkg-core/sources/scriptUtils.ts:77]: I'm not sure why, but my IDE constantly removes those statements by itself. It's technically correct, but really annoying to have those unrelated changes every time I update the file.

Comment (merceyz) [reply packages/yarnpkg-core/sources/scriptUtils.ts:77]: Assuming you're using VSCode, global eslint config or a different extension perhaps?
